### ISSUE TITLE
Валидация полей 'ФИО' : ограничение для полей "ФИО": латиница [A-z], кириллица [А-я], спец символы [-,/ и т д]

### ISSUE THREAD

**Issue by EgorGorbik** [EgorGorbik/software-testing-course#1]
Предусловие:
 1. перейти на страницу https://cs-training-task.qulix.com/trainingtask1/employees
 
Шаги:
 1. открыть форму для добавления персоны (нажав кнопку Добавить)
 2. заполнить все поля формы данными
 3. обратить внимание, что в поля: Имя, Фамилия, Отчество можно вводить цифры

Получено:
 1. Имя, фамилия, отчество может содержать в себе цифры

Ожидаемо:
 1. Имя, фамилия, отчество может состоять только из букв и некоторых спец сиволов(-,/)

**Comment by vliplianina** [comment]
Замечания:
* не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность.
* шаги должны быть пронумерованы
* заголовок не точный. Вероятно, предлагается разрешить ввод только букв. Но в таком случае, в ожидаемом результате необходимо обоснование точки зрения, т.к. букв недостаточно для полноценной работы пользователя с данными полями. Как минимум, возникнет потребность вводить двойные имена через дефис.

**Comment by vliplianina** [comment]
Замечания к исправлению:
1) повторное: не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность"
Как определить серьёзность дефекта: [см. слайд 12 презентации "Регистрация дефектов и запросов на улучшение"](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F%20%D0%B4%D0%B5%D1%84%D0%B5%D0%BA%D1%82%D0%BE%D0%B2%20%D0%B8%20%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2%20%D0%BD%D0%B0%20%D1%83%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%BD%D0%B8%D0%B5.pdf)
Если по какой-то причине не удаётся создать label, то укажите серьёзность текстом в описании дефекта.

2) информация в заголовке расходится с ожидаемым результатом

**Comment by vliplianina** [comment]
Принято.
