### ISSUE TITLE
На форме "Список проектов", таблица смещена вправо

### ISSUE THREAD

**Issue by EgorGorbik** [EgorGorbik/software-testing-course#2]
Шаги: 
 1. открыть страницу https://cs-training-task.qulix.com/trainingtask1/employees
 2. перейти в раздел Проекты

Получено:
 1. таблица всех проектов смещена вправо

Ожидаемо:
 1. таблица всех проектов размещена по центру
![Безымянный](https://user-images.githubusercontent.com/23344375/57334282-f2a3e000-7127-11e9-8a75-4b80d73c9d85.png)

**Comment by vliplianina** [comment]
Необходим скриншот. Остальные замечания см. в issue #1

**Comment by vliplianina** [comment]
Не исправлено замечание:
не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность.
Если по какой-то причине не удаётся создать label, то укажите серьёзность текстом в описании дефекта.

**Comment by vliplianina** [comment]
Принято.
