### ISSUE TITLE
Идентификатор во всех таблицах: при удалении элемента списка id не перерендеривается заново для всех элементов списка

### ISSUE THREAD

**Issue by EgorGorbik** [EgorGorbik/software-testing-course#3]
Шаги:
 1. открываем страницу https://cs-training-task.qulix.com/trainingtask1/
 2. переходим в любой раздел
 3. удаляем элемент таблицы 

Получено: 
 1. идентификаторы остальных элементов остаются такими же

Ожидаемо:
 1. идентификаторы каждого элемента таблицы перерендериваются и выстраиваются в стандартном численном порядке (1,2,3,4 и т. д.)

**Comment by vliplianina** [comment]
Замечания:
* не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность.
* шаги должны быть пронумерованы

**Comment by vliplianina** [comment]
Не исправлено замечание:
"не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность"

Примечание: шаги нумеровать нужно, а ожидаемый и фактический результат только при необходимости.

**Comment by vliplianina** [comment]
Принято.
