### ISSUE TITLE
Отсутствует кнопка перехода на главную страницу во всех разделах приложения

### ISSUE THREAD

**Issue by EgorGorbik** [EgorGorbik/software-testing-course#4]
Шаги:
 1. открыть страницу https://cs-training-task.qulix.com/trainingtask1/
 2. перейти в любой раздел

Получено:
 1. на первоначальную страницу не вернуться никак, кроме как кликать на встроенную в браузер кнопку "<- (назад) "

Ожидаемо:
 1. наличие на каждой странице кнопки "Главная", которая ссылается на главную страницу

**Comment by vliplianina** [comment]
Замечания:
* не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность.
* шаги должны быть пронумерованы
* по структуре заголовка: кнопка "Главная" не является отельным разделом, улучшение актуально для всех разделов, поэтому в начало заголовка название элемента выносить не нужно. Достаточно оставить то, что указано после двоеточия с уточнением  вида "во всех разделах приложения"

**Comment by vliplianina** [comment]
Описание ок, тип задачи верный. Необходимо определить серьёзность. См. комментарии к issue #1

**Comment by vliplianina** [comment]
Принято.
