### ISSUE TITLE
поле "Работа": данное поле не отображается в таблице

### ISSUE THREAD

**Issue by EgorGorbik** [EgorGorbik/software-testing-course#5]
Шаги:
 1. перейти на страницу https://cs-training-task.qulix.com/trainingtask1/
 2. перейти по вкладке Задачи
 3. нажать кнопку Добавить 
 4. заполнить появившуюся форму данными
 5. нажать кнопку "Сохранить"

Получено:
 1. видим таблицу со всеми данными кроме количества часов

Ожидаемо:
 1. отображение количество часов в таблице

**Comment by vliplianina** [comment]
Замечания:
* не соблюдены [требования к оформлению задачи](https://github.com/vliplianina/software-testing-course/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5/labwork2/labwork2.md): не указан тип и не определена серьёзность.
* шаги должны быть пронумерованы
* пропущен шаг сохранения данных формы
* заголовок неверный: поле "Работа" отображается на форме создания задачи, поэтому определение  "нигде" не подходит
* в ожидаемом и полученном результате понятие "время" лучше заменить на "кол-во часов"

**Comment by vliplianina** [comment]
Описание ок. Осталось определить серьёзность дефекта. См. комментарий к issue #1

**Comment by vliplianina** [comment]
Принято.
